
  version: smartide/v0.2
  orchestrator:
    type: docker-compose
    version: 3
  workspace:
    dev-container:
      service-name: smartide-docs
      webide-port: 6800
      ide-type: vscode
      volumes: 
        git-config: true
        ssh-key: true
    services:
  
      smartide-docs:
        image: registry.cn-hangzhou.aliyuncs.com/smartide/smartide-go-opvscode:latest
        restart: always
        environment:
          ROOT_PASSWORD: root123
        volumes:
          - .:/home/project
        expose:
          - 1313
        ports:
          - 1313:1313
        networks:
          - smartide-network
  
    networks:
      smartide-network:
        external: true
