
  version: smartide/v0.2
  orchestrator:
    type: docker-compose
    version: 3
  workspace:
    dev-container:
      service-name: smartide-docs
      webide-port: 6800
      ide-type: vscode
      volumes: 
        git-config: true
        ssh-key: true
    docker-compose-file: docker-compose.yaml
