apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: smartide-go-claim2
  name: smartide-go-claim2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
